const DATABASE_ERROR_CODES = {
  UNIQUE_CONSTRAINT_VIOLATION: "UNIQUE_CONSTRAINT_VIOLATION",
  INVALID_INPUT_SYNTAX: "INVALID_INPUT_SYNTAX",
  DATABASE_EXCEPTION: "DATABASE_EXCEPTION",
} as const;

export { DATABASE_ERROR_CODES };
