const DB_METRICS_OPERATIONS = {
  INSERT: "INSERT",
  UPDATE: "UPDATE",
  FIND: "FIND",
  DELETE: "DELETE",
} as const;

type DB_METRICS_OPERATIONS =
  (typeof DB_METRICS_OPERATIONS)[keyof typeof DB_METRICS_OPERATIONS];

export { DB_METRICS_OPERATIONS };
