const SUBSCRIPTION_INJECTION_TOKENS = {
  SUBSCRIPTION_REPOSITORY: Symbol("SUBSCRIPTION_REPOSITORY"),
  SUBSCRIPTION_EMAIL_CLIENT: Symbol("SUBSCRIPTION_EMAIL_CLIENT"),
  EMAIL_SERVICE: Symbol("EMAIL_SERVICE"),
} as const;

export { SUBSCRIPTION_INJECTION_TOKENS };
