version: "3.9"

services:
  db_test:
    image: postgres:16.4
    container_name: weather-notify-tests
    ports:
      - ${DATABASE_TEST_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_TEST_USER}
      POSTGRES_PASSWORD: ${DATABASE_TEST_PASSWORD}
      POSTGRES_DB: ${DATABASE_TEST_NAME}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - test-network

  test_cache:
    image: redis:7-alpine
    container_name: weather-test-cache
    ports:
      - "6379:6379"
    volumes:
      - cache_test_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - test-network

volumes:
  postgres_test_data:
  cache_test_data:

networks:
  test-network:
    driver: bridge
