version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:7081"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16.4
    restart: always
    container_name: weather-notify
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
