global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["172.31.47.135:9100"]

  - job_name: "weather-notify"
    static_configs:
      - targets: ["localhost:7082"]
    metrics_path: "/metrics"
    scrape_interval: 15s
