const WEATHER_INJECTION_TOKENS = {
  WEATHER_API_PROVIDER: "WEATHER_API_PROVIDER",
  WEATHERBIT_PROVIDER: "WEATHERBIT_PROVIDER",
  WEATHERSTACK_PROVIDER: "WEATHERSTACK_PROVIDER",
  WEATHER_REPOSITORY: "WEATHER_REPOSITORY",
  WEATHER_ERROR_HANDLER: "WEATHER_ERROR_HANDLER",
  FILE_LOGGER: "FILE_LOGGER",
} as const;

export { WEATHER_INJECTION_TOKENS };
