const WEATHER_ERROR_CODES = {
  INVALID_REQUEST: "INVALID_REQUEST",
  CITY_NOT_FOUND: "CITY_NOT_FOUND",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  APP_ERROR: "APP_ERROR",
  PROVIDERS_NOT_AVAILABLE: "PROVIDERS_NOT_AVAILABLE",
} as const;

export { WEATHER_ERROR_CODES };
