const EMAIL_INJECTION_TOKENS = {
  WEATHER_SERVICE: Symbol("WEATHER_SERVICE"),
  EMAIL_WEATHER_CLIENT: Symbol("EMAIL_WEATHER_CLIENT"),
  MESSAGE_BROKER: Symbol("MESSAGE_BROKER"),
} as const;

export { EMAIL_INJECTION_TOKENS };
