const CONFIG_KEYS = {
  EMAIL_SERVICE_HOST: "EMAIL_SERVICE_HOST",
  GRPC_EMAIL_SERVICE_PORT: "GRPC_EMAIL_SERVICE_PORT",
  HTTP_SUBSCRIPTION_SERVICE_PORT: "HTTP_SUBSCRIPTION_SERVICE_PORT",
  WEATHER_SERVICE_HOST: "WEATHER_SERVICE_HOST",
  HTTP_WEATHER_SERVICE_PORT: "HTTP_WEATHER_SERVICE_PORT",
  GRPC_WEATHER_SERVICE_PORT: "GRPC_WEATHER_SERVICE_PORT",
  BASE_URL: "BASE_URL",
  SERVE_ROOT: "SERVE_ROOT",

  DATABASE_NAME: "DATABASE_NAME",
  DATABASE_USER: "DATABASE_USER",
  DATABASE_PASSWORD: "DATABASE_PASSWORD",
  DATABASE_PORT: "DATABASE_PORT",
  DATABASE_HOST: "DATABASE_HOST",

  TEST_DATABASE_NAME: "TEST_DATABASE_NAME",
  TEST_DATABASE_USER: "TEST_DATABASE_USER",
  TEST_DATABASE_PASSWORD: "TEST_DATABASE_PASSWORD",
  TEST_DATABASE_PORT: "TEST_DATABASE_PORT",
  TEST_DATABASE_HOST: "TEST_DATABASE_HOST",

  WEATHER_API_URL: "WEATHER_API_URL",
  WEATHERBIT_URL: "WEATHERBIT_URL",
  WEATHERSTACK_URL: "WEATHERSTACK_URL",
  WEATHER_API_KEY: "WEATHER_API_KEY",
  WEATHERBIT_KEY: "WEATHERBIT_KEY",
  WEATHERSTACK_KEY: "WEATHERSTACK_KEY",

  EMAIL_HOST: "EMAIL_HOST",
  EMAIL_PORT: "EMAIL_PORT",
  EMAIL_USER: "EMAIL_USER",
  EMAIL_PASS: "EMAIL_PASS",
  EMAIL_FROM: "EMAIL_FROM",
  EMAIL_TLS: "EMAIL_TLS",

  REDIS_HOST: "REDIS_HOST",
  REDIS_PORT: "REDIS_PORT",
  CACHE_TTL: "CACHE_TTL",

  TEST_REDIS_HOST: "TEST_REDIS_HOST",
  TEST_REDIS_PORT: "TEST_REDIS_PORT",
  TEST_CACHE_TTL: "TEST_CACHE_TTL",

  KAFKA_HOST: "KAFKA_HOST",
  KAFKA_GROUP_ID: "KAFKA_GROUP_ID",
  EMAIL_TOPIC: "EMAIL_TOPIC",
  SEND_RETRY: "SEND_RETRY",
} as const;

export { CONFIG_KEYS };
