const EMAIL_ERROR_CODES = {
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  DATA_IS_REQUIRED: "DATA_IS_REQUIRED",
  WEATHER_SERVICE_ERROR: "WEATHER_SERVICE_ERROR",
  MESSAGE_BROKER_ERROR: "MESSAGE_BROKER_ERROR",
} as const;

export { EMAIL_ERROR_CODES };
