const SUBSCRIPTION_ERROR_CODES = {
  INVALID_INPUT: "INVALID_INPUT",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  SUBSCRIPTION_ALREADY_CONFIRMED: "SUBSCRIPTION_ALREADY_CONFIRMED",
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
  INVALID_TOKEN: "INVALID_TOKEN",
  EMAIL_SERVICE_ERROR: "EMAIL_SERVICE_ERROR",
  VALIDATION_EXCEPTION: "VALIDATION_EXCEPTION",
} as const;

export { SUBSCRIPTION_ERROR_CODES };
