const WEATHER_INJECTION_TOKENS = {
  WEATHER_API_PROVIDER: "WEATHER_API_PROVIDER",
  WEATHERBIT_PROVIDER: "WEATHERBIT_PROVIDER",
  WEATHERSTACK_PROVIDER: "WEATHERSTACK_PROVIDER",
  WEATHER_REPOSITORY: "WEATHER_REPOSITORY",
} as const;

export { WEATHER_INJECTION_TOKENS };
