const SUBSCRIPTION_ERROR_CODES = {
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  INVALID_INPUT: "INVALID_INPUT",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  SUBSCRIPTION_ALREADY_CONFIRMED: "SUBSCRIPTION_ALREADY_CONFIRMED",
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
  INVALID_TOKEN: "INVALID_TOKEN",
} as const;

export { SUBSCRIPTION_ERROR_CODES };
