const ConfigKeys = {
  PORT: "PORT",
  BASE_URL: "BASE_URL",
  SERVE_ROOT: "SERVE_ROOT",

  DB_NAME: "DATABASE_NAME",
  DB_USER: "DATABASE_USER",
  DB_PASSWORD: "DATABASE_PASSWORD",
  DB_PORT: "DATABASE_PORT",
  DB_HOST: "DATABASE_HOST",

  API_URL: "API_URL",
  API_KEY: "API_KEY",

  EMAIL_HOST: "EMAIL_HOST",
  EMAIL_PORT: "EMAIL_PORT",
  EMAIL_USER: "EMAIL_USER",
  EMAIL_PASS: "EMAIL_PASS",
  EMAIL_FROM: "EMAIL_FROM",
} as const;

export { ConfigKeys };
